### ISSUE TITLE
"No serializable introspection present for type. Consider adding Serdeable" after upgrade to Micronaut 4.0.0-M2/M5

### ISSUE THREAD

**Issue by phlppnhllngr** [micronaut-projects/micronaut-problem-json#257]
### Expected Behavior

The framework should deserialize an object annotated with @io.micronaut.core.annotation.Introspected.

### Actual Behaviour

Deserialization fails with an error:

> Error "i.m.http.server.RouteExecutor - Unexpected error occurred: No deserializable introspection present for type: SomeDto someDto. Consider adding Serdeable.Deserializable annotate to type SomeDto someDto. Alternatively if you are not in control of the project's source code, you can use @SerdeImport(SomeDto.class) to enable deserialization of this type."

### Steps To Reproduce

micronaut-problem 3.0.0-M1 (3.0.0-M2 too) pulls in micronaut-serde-api and micronaut-serde-jackson. After excluding these dependencies the error does not occur:

```
<dependency>
  <groupId>io.micronaut</groupId>
  <artifactId>micronaut-jackson-databind</artifactId>
</dependency>
<dependency>
  <groupId>io.micronaut.problem</groupId>
  <artifactId>micronaut-problem-json</artifactId>
  <exclusions>
    <exclusion>
      <groupId>io.micronaut.serde</groupId>
      <artifactId>micronaut-serde-api</artifactId>
    </exclusion>
    <exclusion>
      <groupId>io.micronaut.serde</groupId>
      <artifactId>micronaut-serde-jackson</artifactId>
    </exclusion>
  </exclusions>
</dependency>
```

Likely related:
<https://github.com/micronaut-projects/micronaut-liquibase/issues/342>

### Environment Information

- JDK 17
- micronaut-parent 4.0.0-M2 with property "micronaut.version" set to 4.0.0-M5
- micronaut-problem-json 3.0.0-M1
- micronaut-jackson-databind

### Version

4.0.0-M5

**Comment by sdelamo** [comment]
@phlppnhllngr thanks for reporting. We will fix this as soon as possible.

**Comment by wetted** [comment]
@phlppnhllngr Have you tried this with the GA release of Micronaut 4.0.0? If it is still a problem can you please provide an example app with a test that exposes the error?

This seems related to #291. I have an example that works at https://github.com/wetted/problemjson291 assuming I understand the issue. Otherwise I need a breaking example.

**Comment by phlppnhllngr** [comment]
Hello @wetted, @StefanSrf just provided an example in #291, please check if you can reproduce the bug with that. If not, i will create a demo project myself and upload it.
